export const errors = {
  USUARIO_EXISTENTE_VERIFICADO : "USUARIO_EXISTENTE_VERIFICADO",
  USUARIO_EXISTENTE_NO_VERIFICADO : "USUARIO_EXISTENTE_NO_VERIFICADO",
  TOKEN_NO_VALIDO : "TOKEN_NO_VALIDO",
  CLAVE_IGUAL_A_ANTERIOR: "CLAVE_IGUAL_A_ANTERIOR",
}